#143 adding section to course dropdown
gurunate/learning-portrait pull request #193
Opened 2024-07-14 21:19 UTC by greenervigil

2024-07-14 22:08 UTC, gurunate requested changes

2024-07-14 22:08 UTC, gurunate commented on app/src/components/course-dropdown/index.tsx
> +    onHandleChange?: (event: SelectChangeEvent) => void;
`onChange` is more accurate.  The handler is passed in by this prop.

2024-07-16 19:15 UTC, hannamlittlefield approved these changes

2024-07-19 19:18 UTC, hannamlittlefield approved these changes

2024-07-21 18:59 UTC, gurunate approved these changes

2024-07-22 01:51 UTC, merged